image: Visual Studio 2017

environment:
  NUGET_API_KEY:
    secure: Mr30wh1prFHq1sfPS7zLxhJp1M8N5qxjQNQthXdCLYAJgOfR9P0uq3iq8UAycN26
  MYGET_API_KEY: dummy

pull_requests:
  do_not_increment_build_number: true

# Is required by SourceLink to have valid file hashes.
# See more detail here: https://github.com/ctaggart/SourceLink/wiki/Line-Endings
init:
  - git config --global core.autocrlf input

build_script:
- ps: |
    & .\build.cmd AppVeyor NuGetPublicKey="$($Env:NUGET_API_KEY)" NuGetPrivateKey="$($Env:MYGET_API_KEY)" BuildVersion=git BuildNumber=$($Env:APPVEYOR_BUILD_NUMBER)

test: off

artifacts:
- path: build\NuGetPackages\*.nupkg
  name: NuGet

deploy: off

